[build]
base = ""
publish = "dist"
command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "http://ec2-98-93-238-165.compute-1.amazonaws.com:8000/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200